spring.application.name=oceanops-cloud
# Database connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/oceanops_cloud}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



logging.level.org.springframework.web=DEBUG
server.error.whitelabel.enabled=false
server.error.include-message=always

openai.api.key=${OPENAI_API_KEY:}
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


